name: Code Formatting

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
        
      - name: Run Biome Check
        run: biome ci .
        
      - name: Fix Formatting Issues (if any)
        if: ${{ failure() }} # Runs only if the previous step fails
        run: |
          echo "Formatting issues detected. Applying fixes..."
          biome format --write
        
      - name: Commit and Push Fixes
        if: ${{ steps.fix.outcome == 'success' }} # Runs only if formatting fixes were applied
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Biome formatting fixes"
          git push
